// Auto-generated by: npm run supabase:types
// Run `npm run supabase:types` after schema changes (requires: supabase login)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      clients: {
        Row: {
          id: string;
          user_id: string;
          first_name: string | null;
          last_name: string | null;
          email: string | null;
          phone: string | null;
          birthday: string | null;
          skin_type: string | null;
          avatar_url: string | null;
          has_routine_access: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          birthday?: string | null;
          skin_type?: string | null;
          avatar_url?: string | null;
          has_routine_access?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          birthday?: string | null;
          skin_type?: string | null;
          avatar_url?: string | null;
          has_routine_access?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      sleep_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          duration: number | null;
          quality: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          duration?: number | null;
          quality?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          duration?: number | null;
          quality?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      sport_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          sport_type_id: string | null;
          duration: number | null;
          intensity: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          sport_type_id?: string | null;
          duration?: number | null;
          intensity?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          sport_type_id?: string | null;
          duration?: number | null;
          intensity?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      meal_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          meal_type: string | null;
          description: string | null;
          photo_url: string | null;
          quality: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          meal_type?: string | null;
          description?: string | null;
          photo_url?: string | null;
          quality?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          meal_type?: string | null;
          description?: string | null;
          photo_url?: string | null;
          quality?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      stress_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          level: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          level?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          level?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      observation_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          positives: string[];
          negatives: string[];
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          positives?: string[];
          negatives?: string[];
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          positives?: string[];
          negatives?: string[];
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      sport_types: {
        Row: {
          id: string;
          name: string;
          icon: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          icon?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          icon?: string | null;
          created_at?: string;
        };
      };
      diagnoses: {
        Row: {
          id: string;
          user_id: string;
          result_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          result_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          result_url?: string | null;
          created_at?: string;
        };
      };
      push_tokens: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          platform: string;
          device_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          platform: string;
          device_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          token?: string;
          platform?: string;
          device_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      app_config: {
        Row: {
          id: string;
          key: string;
          value: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          value?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
