export const ENV = {
  SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL ?? '',
  SUPABASE_PUBLISHABLE_KEY: process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? '',
  TYPEFORM_ID: process.env.EXPO_PUBLIC_TYPEFORM_ID ?? '',
  PRESTASHOP_URL: process.env.EXPO_PUBLIC_PRESTASHOP_URL ?? 'https://skineasy.com',
  SENTRY_DSN: process.env.EXPO_PUBLIC_SENTRY_DSN ?? '',
  DEV_LOGIN_SECRET: process.env.EXPO_PUBLIC_DEV_LOGIN_SECRET ?? '',
  IS_DEV: __DEV__,
};
