import type { LucideIcon } from 'lucide-react-native';
import {
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  Circle,
  CircleDashed,
  CircleDot,
  CircleOff,
  Cloud,
  Droplet,
  Droplets,
  Flame,
  GlassWater,
  Grid3X3,
  Hand,
  Heart,
  Leaf,
  Minimize,
  Minimize2,
  Pill,
  Salad,
  Scale,
  Smile,
  Sparkles,
  Sun,
  Thermometer,
  Waves,
  Zap,
} from 'lucide-react-native';

export const POSITIVE_OBSERVATIONS = [
  'skinHydrated',
  'skinSoothed',
  'smoothSkin',
  'tightPores',
  'fewerImperfections',
  'glowingComplexion',
  'refinedTexture',
  'regulatedSebum',
  'plumpSkin',
  'comfortableSkin',
  'goodDigestion',
] as const;

export const NEGATIVE_OBSERVATIONS = [
  'skinPicking',
  'eczemaFlare',
  'skinInflammation',
  'irritation',
  'acneBreakout',
  'skinReaction',
  'digestiveDiscomfort',
  'microcysts',
  'excessSebum',
  'cloggedPores',
  'tightness',
  'burning',
  'dullComplexion',
  'roughTexture',
  'hyperpigmentation',
  'redness',
] as const;

export type PositiveObservation = (typeof POSITIVE_OBSERVATIONS)[number];
export type NegativeObservation = (typeof NEGATIVE_OBSERVATIONS)[number];

export const POSITIVE_OBSERVATION_ICONS: Record<PositiveObservation, LucideIcon> = {
  skinHydrated: GlassWater,
  skinSoothed: Leaf,
  smoothSkin: AlignCenter,
  tightPores: Minimize,
  fewerImperfections: CircleOff,
  glowingComplexion: Sun,
  refinedTexture: Sparkles,
  regulatedSebum: Scale,
  plumpSkin: Heart,
  comfortableSkin: Smile,
  goodDigestion: Salad,
};

export const NEGATIVE_OBSERVATION_ICONS: Record<NegativeObservation, LucideIcon> = {
  skinPicking: Hand,
  eczemaFlare: AlertCircle,
  skinInflammation: Flame,
  irritation: Zap,
  acneBreakout: CircleDot,
  skinReaction: AlertTriangle,
  digestiveDiscomfort: Pill,
  microcysts: Circle,
  excessSebum: Droplets,
  cloggedPores: Grid3X3,
  tightness: Minimize2,
  burning: Thermometer,
  dullComplexion: Cloud,
  roughTexture: Waves,
  hyperpigmentation: CircleDashed,
  redness: Droplet,
};
